-- ============================================================
-- Friday Football – Supabase Schema
-- Run this in the Supabase SQL editor (Project → SQL Editor)
-- ============================================================

-- Enable UUID generation
create extension if not exists "pgcrypto";

-- ============================================================
-- PROFILES
-- Created automatically after phone OTP sign-up
-- ============================================================
create table profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  phone text unique not null,
  name text not null default '',
  created_at timestamptz default now()
);

-- Auto-create profile row on new auth user
create or replace function handle_new_user()
returns trigger language plpgsql security definer as $$
begin
  insert into profiles (id, phone)
  values (new.id, new.phone)
  on conflict do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure handle_new_user();

-- ============================================================
-- ADMINS
-- Separate pool – only admins can add/remove admins
-- ============================================================
create table admins (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid unique not null references profiles(id) on delete cascade,
  added_by uuid references profiles(id),
  created_at timestamptz default now()
);

-- Helper: is the current user an admin?
create or replace function is_admin()
returns boolean language sql security definer as $$
  select exists (
    select 1 from admins where profile_id = auth.uid()
  );
$$;

-- ============================================================
-- GAMES
-- Created by admins; open to registration once created
-- ============================================================
create table games (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  location text,
  scheduled_at timestamptz not null,
  max_players int not null default 14,
  status text not null default 'open' check (status in ('open', 'closed', 'completed')),
  created_by uuid not null references profiles(id),
  created_at timestamptz default now()
);

-- ============================================================
-- REGISTRATIONS
-- One row per player per game; position determines confirmed vs waitlist
-- ============================================================
create table registrations (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references games(id) on delete cascade,
  profile_id uuid not null references profiles(id) on delete cascade,
  status text not null default 'confirmed' check (status in ('confirmed', 'waitlist')),
  position int not null, -- lower = earlier; drives waitlist order
  added_by uuid references profiles(id), -- null = self-joined; set = admin added
  created_at timestamptz default now(),
  unique (game_id, profile_id)
);

-- ============================================================
-- TEAMS
-- Generated by admin on game day
-- ============================================================
create table teams (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references games(id) on delete cascade,
  name text not null,
  created_at timestamptz default now()
);

create table team_members (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references teams(id) on delete cascade,
  profile_id uuid not null references profiles(id) on delete cascade,
  unique (team_id, profile_id)
);

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

alter table profiles enable row level security;
alter table admins enable row level security;
alter table games enable row level security;
alter table registrations enable row level security;
alter table teams enable row level security;
alter table team_members enable row level security;

-- Profiles: anyone logged in can read; only owner can update their own
create policy "profiles: read all" on profiles for select using (auth.uid() is not null);
create policy "profiles: update own" on profiles for update using (id = auth.uid());

-- Admins: anyone logged in can read; only admins can insert/delete
create policy "admins: read all" on admins for select using (auth.uid() is not null);
create policy "admins: insert" on admins for insert with check (is_admin());
create policy "admins: delete" on admins for delete using (is_admin());

-- Games: anyone logged in can read; only admins can create/update
create policy "games: read all" on games for select using (auth.uid() is not null);
create policy "games: insert" on games for insert with check (is_admin());
create policy "games: update" on games for update using (is_admin());

-- Registrations: anyone logged in can read; insert/delete controlled below
create policy "registrations: read all" on registrations for select using (auth.uid() is not null);
create policy "registrations: self join" on registrations for insert with check (
  profile_id = auth.uid() or is_admin()
);
create policy "registrations: self leave or admin" on registrations for delete using (
  profile_id = auth.uid() or is_admin()
);

-- Teams: anyone logged in can read; only admins can write
create policy "teams: read all" on teams for select using (auth.uid() is not null);
create policy "teams: insert" on teams for insert with check (is_admin());
create policy "team_members: read all" on team_members for select using (auth.uid() is not null);
create policy "team_members: insert" on team_members for insert with check (is_admin());

-- ============================================================
-- SEED: First admin (replace with your actual user UUID after sign-up)
-- INSERT INTO admins (profile_id) VALUES ('<your-uuid>');
-- ============================================================
